# 沙箱账号
natapp: http://wcx64k.natappfree.cc
pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    appid: 2016101200666698
    appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCx2GmcRuwCyJq+NWdymIQmfp4yRKShD6KhMLfrRUsyQq8kvU9MkQRNXYOVon/Vc4L9rRDPWpQwMmhdeQ4uW2rV6sAQQvxbdO6Ab5QB48dg+kUm9sJ9tmPlIJmFOuGkyEnv03jWcZnA+SBJHLZLLr6bfSxKwqsL4s7su1nqf2DyaLlOjJtVOzr4ktLZU1iRJ2OSHrWyjZGQURdEkV2SIVwc6eLdzZtVqcxfbUgixwFl8EEnzMueT8NtZVxxbHSHIguZAzOJ1KGWvAXKh+kwQ1wQOrjRyeB3zMXRuW5FlLatgjeOJfEijb6CbTIRlxqIfWLiwewJcD+uvdcl8sWpFGjAgMBAAECggEBAMEBKHXxJmpu3g/5ulK8tCeXLGZ7d/fPKtm/bAqQS6cxH350cKXPJTuYKf9TKTLmJ2Ibd8wZEzwpjKJ9W0QKGe3q1PtPeTImjeKGz7olg17P0yoktgtNm492rS/SEwAq0nO8UMWzs7FoXgjJwTQJ6s00H39fExhDlEf3qN9LxnXKn5nXzrsbNEUHN3RMtDLOs+kcCJmYWGUsdqpNUGjT1WJvnkWqK4rcpIJAO1LuYK6J/iAC9PtsYRubVTSJcEnI6KTZnx+/eJHd2vEQTp9izlV8uh//92RcWWb5tJMuM267EZwOA21YQgRuZvaGPKaX7MMes0lyXvJd6j9zKeeGOaECgYEA8qSIzqxFf1VYmN+WbxCXgPq3gFp27wMQUW/+wzhCER/Fp9OUZ9PkjeQpaKiZZfI50unwm0tUjuTU/ohlx+5Wfj7smO2Kk46wDW4jPS3cxYEuQyxEkf5B2kT9RMK+d7LP+ytfCduitzqWsTub389LNMk+hQ0Fv3IFonRddPzQ+1UCgYEAzYBSHV5HhMxXeQKh2QHMPlZahf9/uL3dsUFr5U6Em85ZknQ41azjLTC8/qOVnAnVDsjCyek5fAuP5j4yv+rVRvvV+/weMAF/WHxrybGHXeXqRhb/+AinVlEh1MILUlx9/xm9eQz7z6zXRZFwZjHVtvyAjWQDapiH/r5DOXBoyRcCgYEAlF2JDZ6G7EI6Z1en+4eQrBwh4kjuml0sOC+b/rDCrQfZazJTd104To6px0X4bj67nrzPE5XvQWSo3G54ldSlbJJ7R1NQPcOs4LlssLb/XIEN0aMa1o46pAU1PDs8DaL3y2QMu9Fh4Fnh1MNXH3X4TXGUWfTJg/NrgJdYofUIr/UCgYAg5wO+ugKfa4wxzs8VDKmj7XWO8MqFTLj7EWtyCnFG9PH4de1HoOe6q4wHBTAGDLj1JgWyCEpw5vUCO0Eq4zGErPuk3cgDjanTBBDJ+UegLBinYjVXhCMuucy94NepNy/hMUDZ6c9Df/vzooaphh8erizy9mlpnsRfcB0ZTDsqvwKBgEV4SfO4EKdxLpMHVSJDbnXYhpxhVAEQha8Kj9UbA2jrB0d5SBwfyOxfVubCTpRxbmKGi6vcEreGamJpUXZcwd+spkM7P9xtx/rSFRZoUMZdYJLnLZ7qHE4HmX+CMnIclprmkYqiYxoVIBUV9MezznZ/RThN6hxJMUF7+Bkaizr0
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwsdhpnEbsAsiavjVncpiEJn6eMkSkoQ+ioTC360VLMkKvJL1PTJEETV2DlaJ/1XOC/a0Qz1qUMDJoXXkOLltq1erAEEL8W3TugG+UAePHYPpFJvbCfbZj5SCZhTrhpMhJ79N41nGZwPkgSRy2Sy6+m30sSsKrC+LO7LtZ6n9g8mi5ToybVTs6+JLS2VNYkSdjkh61so2RkFEXRJFdkiFcHOni3c2bVanMX21IIscBZfBBJ8zLnk/DbWVccWx0hyILmQMzidShlrwFyofpMENcEDq40cngd8zF0bluRZS2rYI3jiXxIo2+gm0yEZcaiH1i4sHsCXA/rr3XJfLFqRRowIDAQAB
    returnUrl: ${natapp}/alipay/return
    notifyUrl: ${natapp}/alipay/notify

  wxpay:
       appID: wxab8acb865bb1637e
       mchID: 11473623
       key: 2ab9071b06b9f739b950ddb41db2690d
       sandboxKey: 3639bc1370e105aa65f10cd4fef2a3ef
       certPath: /var/local/cert/apiclient_cert.p12
       notifyUrl: http://65ta5j.natappfree.cc/wxpay/refund/notify
       useSandbox: true

server:
  port: 10006
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8


